### PR TITLE
Changing text for updating/replacing files

### PR DESCRIPTION
**Pull request by jakub-pomykala**

### CODE REVIEW

**Review by gkwan-ibm — CHANGES_REQUESTED** [review]
hi @jabcuga need to add guide-getting-started.md?

**Comment by gkwan-ibm** [comment]
> hi @jabcuga need to add guide-getting-started.md?

Sorry @jabcuga, I tagged you incorrectly.

**Review by gkwan-ibm — APPROVED** [review]

**Review by gkwan-ibm — CHANGES_REQUESTED** [review]
an extra `\` char after the word "select"

**Comment by jakub-pomykala** [comment]
@gkwan-ibm I merged the PR to staging to verify on the staging portal. Find PR [here](https://github.com/OpenLiberty/cloud-hosted-guides/pull/1161/files)

**Review by gkwan-ibm — APPROVED** [review]

**Pull request merged**
